version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./local.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  backend-code: 
  frontend-code: 
  node-modules:
