version: "3"

services:
  db:
    image: postgres:latest
    platform: linux/amd64
    env_file:
      - ./local.env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./local.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  db-data:
  backend-code:
  frontend-code:
  node-modules:
